import { invoke } from '@tauri-apps/api/core';
import type { Task, TaskInput, Note, NoteInput, Link, LinkInput, Board, BoardInput, Habit, HabitInput, HabitLog } from '../types';

export const api = {
  taskList: () => invoke<Task[]>('task_list'),
  taskCreate: (input: TaskInput) => invoke<Task>('task_create', { input }),
  taskUpdate: (task: Task) => invoke<Task>('task_update', { task }),
  taskDelete: (id: string) => invoke<void>('task_delete', { id }),
  boardList: () => invoke<Board[]>('board_list'),
  boardCreate: (input: BoardInput) => invoke<Board>('board_create', { input }),
  boardRename: (id: string, name: string) => invoke<Board>('board_rename', { id, name }),
  boardDelete: (id: string) => invoke<void>('board_delete', { id }),
  habitList: () => invoke<Habit[]>('habit_list'),
  habitCreate: (input: HabitInput) => invoke<Habit>('habit_create', { input }),
  habitUpdate: (habit: Habit) => invoke<Habit>('habit_update', { habit }),
  habitDelete: (id: string) => invoke<void>('habit_delete', { id }),
  habitToggle: (id: string, date: string) => invoke<HabitLog | null>('habit_toggle', { id, date }),
  habitLogs: (from: string, to: string) => invoke<HabitLog[]>('habit_logs', { from, to }),
  noteList: () => invoke<Note[]>('note_list'),
  noteCreate: (input: NoteInput) => invoke<Note>('note_create', { input }),
  noteUpdate: (note: Note) => invoke<Note>('note_update', { note }),
  noteDelete: (id: string) => invoke<void>('note_delete', { id }),
  linkList: () => invoke<Link[]>('link_list'),
  linkCreate: (input: LinkInput) => invoke<Link>('link_create', { input }),
  linkUpdate: (link: Link) => invoke<Link>('link_update', { link }),
  linkDelete: (id: string) => invoke<void>('link_delete', { id }),
  linkMove: (id: string, sortOrder: number) => invoke<void>('link_move', { id, sortOrder }),
  linkOpen: (kind: string, target: string) => invoke<void>('link_open', { kind, target }),
  linkRun: (id: string) => invoke<void>('link_run', { id }),
  settingsAll: () => invoke<Record<string, string>>('settings_all'),
  settingsSet: (key: string, value: string) => invoke<void>('settings_set', { key, value }),
  backupExport: (path: string) => invoke<void>('backup_export', { path }),
  backupImport: (path: string) => invoke<number>('backup_import', { path }),
};
